
# ZSH CONFIG

# Path to OHMYZSH
export ZSH="$HOME/.oh-my-zsh"

# ZSH Theme
ZSH_THEME="robbyrussell"

# Plugins
plugins=(git zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

# $HOME Path
export PATH="$HOME/.local/bin:$PATH"

# Aliases
alias zshconfig="$EDITOR $HOME/.zshrc"
alias ohmyzsh="$EDITOR $HOME/.oh-my-zsh"
alias restartzsh="source $HOME/.zshrc"
alias emacsconfig="$EDITOR $HOME/.config/emacs"

# NixOS Configuration
alias nixosconfig="sudoedit /etc/nixos/configuration.nix"

# VSCodim
# export PATH="$HOME/.local/share/bin/vscodium:$PATH"
alias code="codium"

# Hyprland configuration
alias hyprlandconfig="$EDITOR $HOME/.config/hypr/hyprland.conf"
alias hyprpaperconfig="$EDITOR $HOME/.config/hypr/hyprpaper.conf"

# asdf
# export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"

# cargo
# export PATH="$HOME/.cargo/bin:$PATH"

# opencode
# export PATH="$HOME/.opencode/bin:$PATH"
